name: publish synapse workspace

on:
  workflow_dispatch:  # allows manual trigger
  push:
    branches:
      - main  # or dev (where your dev workspace syncs from)

jobs:
  publish:
    runs-on: windows-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Azure Login
        uses: azure/login@v1
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}

      - name: Publish Synapse Workspace Artifacts
        uses: azure/synapse-artifacts-publish@v1.0
        with:
          SynapseWorkspaceName: 'synapse-dev-wrksp'
          TargetFolder: './synapse-dev-wrksp'
          environment: 'Azure Public'
          resourceGroup: 'shruti_09_rg'
          subscriptionId: ${{ secrets.SUBSCRIPTIONID }}
          tenantId: ${{ secrets.TENANTID }}

      - name: Commit and push exported templates
        run: |
          git config user.name "github-actions"
          git config user.email "github-actions@github.com"
          git add .
          git commit -m "Published Synapse workspace artifacts"
          git push origin workspace_publish
