name: workspace deployment

on:
    workflow_dispatch:  # allows manual trigger
    push:
        branches: [ workspace_publish ]
jobs:
    release:
        # You also can use the self-hosted runners.
        runs-on: windows-latest
        steps:
        # Checks out your repository under $GITHUB_WORKSPACE, so your job can access it.
          - uses: actions/checkout@v2
          - uses: azure/synapse-workspace-deployment@release-1.0
        with:
          TargetWorkspaceName: 'synapse-uat-wrksp'
          TemplateFile: './synapse-dev-wrksp/TemplateForWorkspace.json'
          ParametersFile: './synapse-dev-wrksp/TemplateParametersForWorkspace.json'
          OverrideArmParameters: './parameters.yaml'
          environment: 'Azure Public'
          resourceGroup: 'shruti_09_rg'
          clientId: ${{secrets.CLIENTID}}
          clientSecret:  ${{secrets.CLIENTSECRET}}
          subscriptionId: 'subscriptionId of the target workspace'
          tenantId: 'tenantId'
          DeleteArtifactsNotInTemplate: 'true'
          managedIdentity: 'False'
